### ISSUE TITLE
Tower, Ground and Delivery role not showing up in the APAC region.

### ISSUE THREAD

**Issue by BokBoy** [maiuswong/simaware-express#101] opened 2024-01-25 10:03 UTC
Hi all,
I've been using Simaware for a while now and only recently noticed that the T, G and D roles are not showing up on Australia, even though it is online. The ATIS shows up, as you can see. I just flew into YSCB (image below) and the Tower was online but only the ATIS is showing up. 
This only affects T, G and D roles not Centre, Approach or Departures.
![image](https://github.com/maiuswong/simaware-express/assets/132247243/d16bf92f-1664-431d-aff1-b68c9e62c00d)
Thanks!!

**Comment by BokBoy** [comment] 2024-01-25 10:04
Oh yeah, in console, I'm getting error - Patrons is not defined, if that helps

**Comment by BokBoy** [comment] 2024-01-25 10:13
Right, APAC region all use VATSYS, its a forced client by the division directors.

**Comment by kenkam** [comment] 2024-01-25 21:37
> Oh yeah, in console, I'm getting error - Patrons is not defined, if that helps

This is fixed in #99

**Comment by BokBoy** [comment] 2024-01-26 00:51
> > Oh yeah, in console, I'm getting error - Patrons is not defined, if that helps
> 
> 
> 
> This is fixed in #99, although I think it is unrelated to your specific issue.

Yea I'm thinking this isn't related but thought I may as well mention this.

**Comment by AgentWolfFBI** [comment] 2024-01-26 04:13
> Right, APAC region all use VATSYS, its a forced client by the division directors, and our callsigns aren't icao_twr or icao_gnd, its SY_GND or ML_TWR, depending on location
As far as I'm aware, this is the reason why. As you said, SY_TWR as opposed to YSSY_TWR is causing issues, for example. VatSpy doesn't have this issue with aerodrome stations.

Another more complicated issue is extended FIR sectors in APAC, whereby a controller may extend their services to multiple sectors surrounding their primary sector. The only way for Simaware (& other VATSIM maps) to show the extended sectors as staffed would be to identify which frequencies are actively in use --- while extending, controllers cross-couple frequencies from multiple sectors. VATPAC has already written code to do this for their own coverage map; perhaps this could be integrated into SimAware at some point?

I think a far greater issue is the aerodrome stations though as this is a direct misrepresentation of coverage. I wouldn't consider myself an expert, however it doesn't seem to be a particularly complex issue to solve if it's simply the naming convention causing the problem.

**Comment by BokBoy** [comment] 2024-01-26 07:01
> Right, APAC region all use VATSYS, its a forced client by the division directors, and our callsigns aren't icao_twr or icao_gnd, its SY_GND or ML_TWR, depending on location
> As far as I'm aware, this is the reason why. As you said, SY_TWR as opposed to YSSY_TWR is causing issues, for example. VatSpy doesn't have this issue with aerodrome stations.
> Another more complicated issue is extended FIR sectors in APAC, whereby a controller may extend their services to multiple sectors surrounding their primary sector. The only way for Simaware (& other VATSIM maps) to show the extended sectors as staffed would be to identify which frequencies are actively in use --- while extending, controllers cross-couple frequencies from multiple sectors. VATPAC has already written code to do this for their own coverage map; perhaps this could be integrated into SimAware at some point?

Hmm... the first one could possibly be solved by checking the controller description as the controller normally puts - "extending to" then a list like ELW, BIK...

**Comment by maiuswong** [comment] 2024-01-28 15:19
This may be fixed; the prefix was being pulled from an old airports.json and not the one that is updated nightly.  Since it's 2AM over there I'll leave this open until it's confirmed fixed.

**Comment by BokBoy** [comment] 2024-01-28 21:33
> This may be fixed; the prefix was being pulled from an old airports.json and not the one that is updated nightly.  Since it's 2AM over there I'll leave this open until it's confirmed fixed.

Good morning to you too. It is 2 am AEDT when you sent that. We can try this tonight (more like morning for Zulu time) as we have a milk run Monday at 0830-1130 Zulu. If it works, I'll send an update here. Thanks!!

**Comment by BokBoy** [comment] 2024-01-29 07:53
Sadly not fixed
![image](https://github.com/maiuswong/simaware-express/assets/132247243/20bc2d40-1210-4db8-a2c1-cad85381c1e9)
![image](https://github.com/maiuswong/simaware-express/assets/132247243/e1e72997-17c3-4c3b-8812-3e715adf6ab5)

**Comment by AgentWolfFBI** [comment] 2024-01-29 08:16
> Hmm... the first one could possibly be solved by checking the controller description as the controller normally puts - "extending to" then a list like ELW, BIK...
Probably not feasible unfortunately. Most controllers include this (they should), but many don't. And the structure varies among those who do (e.g. some include the frequencies as well, others don't bother).

**Comment by BokBoy** [comment] 2024-01-29 08:49
> > Hmm... the first one could possibly be solved by checking the controller description as the controller normally puts - "extending to" then a list like ELW, BIK...
> 
> Probably not feasible unfortunately. Most controllers include this (they should), but many don't. And the structure varies among those who do (e.g. some include the frequencies as well, others don't bother).

Most controllers do it...
![image](https://github.com/maiuswong/simaware-express/assets/132247243/3eb95ec4-96b2-4c9c-bb9f-fc7accfab47a)

**Comment by BokBoy** [comment] 2024-02-03 07:53
Uhh @maiuswong it randomly fixed on my end...
Thanks for the help, I'm going to keep this open for the extending to part. Thanks!!

**Comment by AgentWolfFBI** [comment] 2024-02-03 09:37
> Uhh @maiuswong it randomly fixed on my end... Thanks for the help, I'm going to keep this open for the extending to part. Thanks!!

Still not fixed, but it's gone back to how it was a few months ago whereby it seems the major Class C aerodromes (Sydney, Mlebourne, etc) show up find but not the rest. See attached screenshot
![VatSpy](https://github.com/maiuswong/simaware-express/assets/61309999/03445561-4269-4a47-bcfd-ab7279404210)
![SimAware](https://github.com/maiuswong/simaware-express/assets/61309999/a466a759-054b-46a5-a4f8-56bc106b7b77)

**Comment by BokBoy** [comment] 2024-02-03 09:52
> > Uhh @maiuswong it randomly fixed on my end... Thanks for the help, I'm going to keep this open for the extending to part. Thanks!!
> 
> 
> 
> Still not fixed, but it's gone back to how it was a few months ago whereby it seems the major Class C aerodromes (Sydney, Mlebourne, etc) show up fine but not the rest. See attached screenshot
> 
> ![VatSpy](https://github.com/maiuswong/simaware-express/assets/61309999/03445561-4269-4a47-bcfd-ab7279404210)
> 
> ![SimAware](https://github.com/maiuswong/simaware-express/assets/61309999/a466a759-054b-46a5-a4f8-56bc106b7b77)


I stand corrected, I was wondering why YWMW or whatever the ICAO was wasn't showing up, thought it was server lag or smth (flew to Sydney from Canberra on Vatsim just then)

**Closed** 2024-02-06 02:25 UTC
Labels: bug

**Comment by BokBoy** [comment] 2024-02-06 04:12
Thanks mate will open new issue for the extending too one.
